name = input("이름을 입력하세요 : ")
address = input("주소를 입력하세요 : ")
tel = input("전화번호를 입력하세요 : ")
# print("- 이름 : %s \n - 주소 : %s \n - 전화번호 : %s" %(name, address, tel))
print("- 이름 :", name)
print("- 주소 :", address)
print("- 전화번호 :", tel)